/*
**  mod_osrm.c -- Apache sample osrm module
**  [Autogenerated via ``apxs -n osrm -g'']
**
**  To play with this sample module first compile it into a
**  DSO file and install it into Apache's modules directory
**  by running:
**
**    $ apxs -c -i mod_osrm.c
**
**  Then activate it in Apache's apache2.conf file for instance
**  for the URL /osrm in as follows:
**
**    #   apache2.conf
**    LoadModule osrm_module modules/mod_osrm.so
**    <Location /osrm>
**    SetHandler osrm
**    </Location>
**
**  Then after restarting Apache via
**
**    $ apachectl restart
**
**  you immediately can request the URL /osrm and watch for the
**  output of this module. This can be achieved for instance via:
**
**    $ lynx -mime_header http://localhost/osrm
**
**  The output should be similar to the following one:
**
**    HTTP/1.1 200 OK
**    Date: Tue, 31 Mar 1998 14:42:22 GMT
**    Server: Apache/1.3.4 (Unix)
**    Connection: close
**    Content-Type: text/html
**
**    The sample page from mod_osrm.c
*/

#include "httpd.h"
#include "http_config.h"
#include "http_protocol.h"
#include "ap_provider.h"
#include "ap_config.h"

#include <unistd.h>
#include <stdlib.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <sys/un.h>
#include <stdio.h>
#include <netinet/in.h>


void sendBytes(int client, const void* bytes, int length)
{
    // prepare to send request
    int nleft = length;


    int nwritten;
    // loop to be sure it is all sent
    while (nleft)
    {
        if ((nwritten = send(client, bytes, nleft,0)) < 0)
        {
            if (errno == EINTR)
            {
                // the socket call was interrupted -- try again
                continue;
            }
            else
            {
                // an error occurred, so break out
                return;
            }
        }
        else if (nwritten == 0)
        {
            // the socket is closed
            return;
        }
        nleft -= nwritten;
        bytes += nwritten;
    }
    return;
}

void sendRequest(int client, const char* request)
{
    int requestLength = htonl(strlen(request));
    sendBytes(client, &requestLength, sizeof(int));
    sendBytes(client, request, strlen(request));
}

void readBytes(int client, void* buffer, int length)
{

    int nread = recv(client,buffer,length,0);

    if (nread < 0)
    {
        return;
    }
    else if (nread == 0)
    {
        // the socket is closed
        return;
    }

    return;
}

char* getResponse(int client)
{
    int requestLength = 0;
    readBytes(client,&requestLength, sizeof(int));
    requestLength = ntohl(requestLength);

    char* buffer =  malloc(requestLength);
    readBytes(client, buffer, requestLength);
    return buffer;
}

char* communicateWithOSRMd(const char* server, const char* request)
{
    int client, servlen, bytesLenght;
    struct sockaddr_un server_address;

    bzero((char *)&server_address, sizeof(server_address));
    server_address.sun_family = AF_UNIX;
    strcpy(server_address.sun_path, server);
    servlen = strlen(server_address.sun_path) + sizeof(server_address.sun_family);

    if((client = socket(AF_UNIX, SOCK_STREAM, 0)) < 0)
        return 0; //error creating socket

    if(connect(client, (struct sockaddr *) &server_address, servlen) < 0)
        return 0; //error connecting

    sendRequest(client, request);

    char* response = getResponse(client);

    close(client);

    return response;
}

/*
    Configuration prototype and declaration;
*/
typedef struct
{
    const char *osrmd_socket_path;
} mod_osrm_config;

static mod_osrm_config config;

/*
    Handler for OSRMdSocketName
*/
const char *mod_osrm_set_osrmd_socket_path(cmd_parms *cmd, void *cfg, const char *arg)
{
    config.osrmd_socket_path = arg;
    return NULL;
}

/*
    The directive structure for name tag
*/
static const command_rec mod_osrm_directives[] =
{
    AP_INIT_TAKE1("OSRMdSocketName", mod_osrm_set_osrmd_socket_path,NULL,RSRC_CONF,"The name of the unix socket for OSRMd"),
    {NULL}
};


/*
    Content handler
*/
static int mod_osrm_handler(request_rec *r)
{
    if (strcmp(r->handler, "osrm")) {
        return DECLINED;
    }
    r->content_type = "application/json;charset=utf-8";

    if (!r->header_only)
    {
//        ap_rputs("The sample page from mod_osrm.c <br/>", r);
//        ap_rputs("You requested: ",r);
//
//        //r->uri (ex.: /viaroute) without first character + "?" + r->args (ex.: loc=12.213,12.432)

        if(r->args)
        {
            int requestLength = strlen(r->uri) + strlen(r->args) + 1;
            char queryString[requestLength];

            strcpy(queryString, r->uri);
            strcat(queryString, "?");
            strcat(queryString, r->args);

            char* response = communicateWithOSRMd(config.osrmd_socket_path,queryString);

            ap_rputs(response,r);

            free(response);
        }
        else
        {
            r->status = 500;
            ap_rputs("Bad Request",r);
        }



//
//        if(r->args)
//        {
//            ap_rputs(r->args,r);
//        }
//
//
//        ap_rputs("<br/>",r);
//        ap_rputs("Socket name: ",r);
//        ap_rputs(config.osrmd_socket_path,r);
//        ap_rputs("<br/>",r);


    }

    return OK;
}

static void osrm_register_hooks(apr_pool_t *p)
{
    config.osrmd_socket_path = "/tmp/osrmd.sock";
    ap_hook_handler(mod_osrm_handler, NULL, NULL, APR_HOOK_MIDDLE);
}

/* Dispatch list for API hooks */
module AP_MODULE_DECLARE_DATA osrm_module = {
    STANDARD20_MODULE_STUFF,
    NULL,                  /* create per-dir    config structures */
    NULL,                  /* merge  per-dir    config structures */
    NULL,                  /* create per-server config structures */
    NULL,                  /* merge  per-server config structures */
    mod_osrm_directives,   /* table of config file commands       */
    osrm_register_hooks    /* register hooks                      */
};
